name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: urlshortener
          POSTGRES_PASSWORD: urlshortener
          POSTGRES_DB: urlshortener
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U urlshortener"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    env:
      DATABASE_URL: postgres://urlshortener:urlshortener@localhost:5432/urlshortener
      JWT_SECRET: test_secret
      BASE_URL: http://localhost:3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Wait for Postgres (sleep)
        run: sleep 10

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run Prisma migrations
        run: npx prisma migrate deploy

      - name: Build Auth Service
        run: npm run build:auth

      - name: Start Auth Service
        run: node dist/apps/auth-service/main.js &
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          JWT_SECRET: ${{ env.JWT_SECRET }}

      - name: Wait for Auth Service
        run: sleep  10

      - name: Build URL Shortener Service
        run: npm run build:url-shortener

      - name: Run Unit Tests
        run: npm run test

      - name: Run E2E Tests
        run: npm run test:e2e